### ISSUE TITLE
Errors when loading pre-trained models

### ISSUE THREAD

**Issue by wangdeze18** [giganticode/probes#1]
Thanks a lot for your great work.  I met errors when loading CodeT5, PLBART-mtjava and PLBART-large models.
For codet5, I change the code as follows:
`tokenizer = RobertaTokenizer.from_pretrained(modelname, cache_dir="~/tmp")
model = T5ForConditionalGeneration.from_pretrained(modelname, config=config, cache_dir="~/tmp")
`

For PLBART-mtjava and PLBART-large models,  I found a useful [issue](https://github.com/wasiahmad/PLBART/issues/28#issuecomment-1072984961)

**Comment by anjandash** [comment]
Hi @wangdeze18 

Thanks for your interest, the current version of the code should work.  
Both CodeT5 and PLBART models can now be loaded with a Seq2SeqLM head.
